### PR TITLE
Ensure completion handler is called

### PR DESCRIPTION
**Pull request by wmcginty**

### CODE REVIEW

**Review by tylermilner — DISMISSED** [review]
I don't suppose there's any way to easily make a unit test for this? 😁

**Comment by wmcginty** [comment]
There's probably quite a bit of testing that can be done, but I figured I'd get the bug fix in quickly, then test later.

**Comment by tylermilner** [comment]
Ah, the classic "fix now, test later" excuse. 😜

**Comment by wmcginty** [comment]
Exactly 😄 . I did however add a changelog entry @tylermilner

**Review by tylermilner — APPROVED** [review]

**Pull request merged**
